Test
BMSTU-2019-LAB/02-lab-04-templates-matrix-Robert29000 pull request #12
Opened 2020-03-24 18:46 UTC by Robert29000

2020-04-19 11:43 UTC, krygin requested changes

2020-04-19 11:43 UTC, krygin commented on include/matrix.hpp
> + this -> p = reinterpret_cast<T**>(malloc(rows * sizeof(T *)));
Давай всё же на new / delete переделаем

2020-04-19 11:43 UTC, krygin commented on include/matrix.hpp
> +bool operator==(const Matrix<double> &m1, const Matrix<double> &m2){
Хорошее решение.

Еще можно было написать всё в одной функции:
```
if (std::is_floating_point<T>::value) {
// реализация для float и double
} else {
// реализация для целых чисел
}
```

2020-04-19 18:56 UTC, Robert29000 commented on include/matrix.hpp
> + this -> p = reinterpret_cast<T**>(malloc(rows * sizeof(T *)));
Понял
Переделал

2020-05-10 19:34 UTC, krygin approved these changes

2020-05-10 19:34 UTC, merged